package gitp.scrapingbatch.request

object TestSampleContainer {
    /**
     * 3 lecture response element
     * contains 2 closed lecture
     */


    val simpleLectureResponse = """
        [
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "월3,4/수4",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "01",
            "hy": "0",
            "subsrtDivCd": "FR",
            "subjtnb": "UCB1110",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "블랜디드(동영상) ",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "절대평가",
            "cdt": 3,
            "srclnLctreYn": "0",
            "rcognHrs": 3,
            "cgprfNm": "양희진",
            "subjtChngGudncDivCdPr": null,
            "timtbDplctPermKindCd": null,
            "atntnMattrDesc": null,
            "usubjtnb": "U00088",
            "lctreTimeEngNm": "Mon3,4/Wed4",
            "rmvlcYn": "0",
            "excstPercpFg": "1",
            "subjtNm": "미학",
            "lecrmNm": "교302/동영상콘텐츠",
            "rmvlcYnNm": " ",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "1",
            "estblDeprtCd": "30109",
            "subjtNm2": "미학",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": "Yang HeeJin",
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 90,
            "subjtnbCorsePrcts": "UCB1110-01-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "대학교양(2019학번~) 문학과예술",
            "subjtEngNm": "AESTHETICS",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": null,
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "0",
            "subsrtDivNm": "대교",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        },
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "화2,3/목1",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "01",
            "hy": "0",
            "subsrtDivCd": "FR",
            "subjtnb": "UCE1105",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "블랜디드(동영상) ",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "절대평가",
            "cdt": 3,
            "srclnLctreYn": "0",
            "rcognHrs": 3,
            "cgprfNm": "강철",
            "subjtChngGudncDivCdPr": null,
            "timtbDplctPermKindCd": null,
            "atntnMattrDesc": null,
            "usubjtnb": "U00283",
            "lctreTimeEngNm": "Tue2,3/Thu1",
            "rmvlcYn": "0",
            "excstPercpFg": "1",
            "subjtNm": "영화의이해",
            "lecrmNm": "광B105/동영상콘텐츠",
            "rmvlcYnNm": " ",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "1",
            "estblDeprtCd": "30109",
            "subjtNm2": "영화의이해",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": "Kang  Chul",
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 90,
            "subjtnbCorsePrcts": "UCE1105-01-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "대학교양(2019학번~) 문학과예술",
            "subjtEngNm": "UNDERSTANDING ON CINEMA",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": null,
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "0",
            "subsrtDivNm": "대교",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        },
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "수5,금5,6",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "02",
            "hy": "0",
            "subsrtDivCd": "FR",
            "subjtnb": "UCE1105",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "대면강의",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "절대평가",
            "cdt": 3,
            "srclnLctreYn": "0",
            "rcognHrs": 3,
            "cgprfNm": "김동호",
            "subjtChngGudncDivCdPr": null,
            "timtbDplctPermKindCd": null,
            "atntnMattrDesc": null,
            "usubjtnb": "U00283",
            "lctreTimeEngNm": "Wed5,Fri5,6",
            "rmvlcYn": "0",
            "excstPercpFg": "1",
            "subjtNm": "영화의이해",
            "lecrmNm": "광B105",
            "rmvlcYnNm": " ",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "1",
            "estblDeprtCd": "30109",
            "subjtNm2": "영화의이해",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": "KIM DONG HO",
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 90,
            "subjtnbCorsePrcts": "UCE1105-02-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "대학교양(2019학번~) 문학과예술",
            "subjtEngNm": "UNDERSTANDING ON CINEMA",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": null,
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "0",
            "subsrtDivNm": "대교",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        },
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "수3/금3,4",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "01",
            "hy": "0",
            "subsrtDivCd": "FR",
            "subjtnb": "UCE1107",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "블랜디드(동영상) ",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "절대평가",
            "cdt": 3,
            "srclnLctreYn": "0",
            "rcognHrs": 3,
            "cgprfNm": "지형주",
            "subjtChngGudncDivCdPr": null,
            "timtbDplctPermKindCd": null,
            "atntnMattrDesc": "음악대학 소속학생 수강불가",
            "usubjtnb": "U00287",
            "lctreTimeEngNm": "Wed3/Fri3,4",
            "rmvlcYn": "0",
            "excstPercpFg": "1",
            "subjtNm": "음악사",
            "lecrmNm": "교102/동영상콘텐츠",
            "rmvlcYnNm": " ",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "1",
            "estblDeprtCd": "30109",
            "subjtNm2": "음악사",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": "Chi Hyungjoo",
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 90,
            "subjtnbCorsePrcts": "UCE1107-01-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "대학교양(2019학번~) 문학과예술",
            "subjtEngNm": "HISTORY OF MUSIC",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": null,
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "0",
            "subsrtDivNm": "대교",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        },
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "금6,7/금8",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "01",
            "hy": "2",
            "subsrtDivCd": "FR",
            "subjtnb": "EDU2002",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "블랜디드(동영상) ",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": "1",
            "gradeEvlMthdDivNm": "절대평가",
            "cdt": 3,
            "srclnLctreYn": "0",
            "rcognHrs": 3,
            "cgprfNm": "이무성,장원섭,황금중,박순용,이규민,서영석,이병식,김성원,오석영,류지훈,김남주,하효림,황순예",
            "subjtChngGudncDivCdPr": "1",
            "timtbDplctPermKindCd": null,
            "atntnMattrDesc": "교육학부 전공필수 및 필수교양(대학) 교차인정 가능",
            "usubjtnb": "J00055",
            "lctreTimeEngNm": "Fri6,7/Fri8",
            "rmvlcYn": "0",
            "excstPercpFg": "0",
            "subjtNm": "미래를위한교육학",
            "lecrmNm": "교306/동영상(중복수강불가)",
            "rmvlcYnNm": " ",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "1",
            "estblDeprtCd": "30113",
            "subjtNm2": "미래를위한교육학",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": "Lee Moosung/Chang, Wonsup/Hwang Keumjoong/Pak Soon-Yong/LEE GUEMIN/Seo Young Seok/Rhee Byung Shik/Kim Sung won/Oh Seok Young/Ryoo Ji Hoon/Kim Nam Ju/HA HYO RIM/Hwang Soon Ye",
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 130,
            "subjtnbCorsePrcts": "EDU2002-01-00",
            "subjtUnitVal": "2000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "대학교양(2019학번~) 국가와사회",
            "subjtEngNm": "EDUCATION FOR TOMORROW",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": "Edu306/Pre-recorded lecture(Unable to take other class)",
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "1",
            "subsrtDivNm": "대교",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        }
    ]
    """.trimIndent()
    val lectureResponseContainsClosedClasses = """
      [
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "수10",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "04",
            "hy": "0,2,3,4,5",
            "subsrtDivCd": "FP",
            "subjtnb": "YCA1003",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "대면강의",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "P/NP",
            "cdt": 0,
            "srclnLctreYn": "0",
            "rcognHrs": 1,
            "cgprfNm": null,
            "subjtChngGudncDivCdPr": null,
            "timtbDplctPermKindCd": "10",
            "atntnMattrDesc": null,
            "usubjtnb": "U00001",
            "lctreTimeEngNm": "Wed10",
            "rmvlcYn": "1",
            "excstPercpFg": "0",
            "subjtNm": "채플(3)",
            "lecrmNm": null,
            "rmvlcYnNm": "폐강",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "3",
            "estblDeprtCd": "30105",
            "subjtNm2": "채플(3)",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": null,
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 40,
            "subjtnbCorsePrcts": "YCA1003-04-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "교양기초(2019학번~) 채플",
            "subjtEngNm": "CHAPEL(3)",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": null,
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "0",
            "subsrtDivNm": "교기",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        },
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "수10",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "04",
            "hy": "0,3,2,4,5",
            "subsrtDivCd": "FP",
            "subjtnb": "YCA1007",
            "experPrctsAmt": 0,
            "subjtSbtlNm": null,
            "subjtClNm": "대면강의",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "P/NP",
            "cdt": 0.5,
            "srclnLctreYn": "0",
            "rcognHrs": 1,
            "cgprfNm": null,
            "subjtChngGudncDivCdPr": null,
            "timtbDplctPermKindCd": "10",
            "atntnMattrDesc": null,
            "usubjtnb": "U00001",
            "lctreTimeEngNm": "Wed10",
            "rmvlcYn": "1",
            "excstPercpFg": "0",
            "subjtNm": "채플(C)",
            "lecrmNm": null,
            "rmvlcYnNm": "폐강",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "3",
            "estblDeprtCd": "30105",
            "subjtNm2": "채플(C)",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": null,
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 40,
            "subjtnbCorsePrcts": "YCA1007-04-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "교양기초(2019학번~) 채플",
            "subjtEngNm": "CHAPEL(C)",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": null,
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "0",
            "subsrtDivNm": "교기",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        },
        {
            "lawscSubjcgpNm": null,
            "srclnLctreLangDivCd": null,
            "coprtEstblYn": "0",
            "smtDivCd": "10",
            "lessnSessnDivCd": "A",
            "lctreTimeNm": "일1",
            "lawscSubjcFldNm": null,
            "corseDvclsNo": "02",
            "hy": "0,2,3,4,5",
            "subsrtDivCd": "FP",
            "subjtnb": "YCA1003",
            "experPrctsAmt": 0,
            "subjtSbtlNm": "(비대면)",
            "subjtClNm": "비대면(동영상) ",
            "campsDivNm": "신촌",
            "syllaUnregTrgetDivCd": "0",
            "subjtChngGudncDivCdTm": null,
            "onppsPrttnAmt": 0,
            "subjtChngGudncDivCdPl": null,
            "gradeEvlMthdDivNm": "P/NP",
            "cdt": 0,
            "srclnLctreYn": "0",
            "rcognHrs": 1,
            "cgprfNm": "정미현,김동환",
            "subjtChngGudncDivCdPr": "1",
            "timtbDplctPermKindCd": "10",
            "atntnMattrDesc": "초과학기생 수강가능",
            "usubjtnb": "U00001",
            "lctreTimeEngNm": "Sun1",
            "rmvlcYn": "0",
            "excstPercpFg": "0",
            "subjtNm": "채플(3)(비대면)",
            "lecrmNm": "동영상콘텐츠",
            "rmvlcYnNm": " ",
            "medcHyLisup": null,
            "gradeEvlMthdDivCd": "3",
            "estblDeprtCd": "30105",
            "subjtNm2": "채플(3)",
            "syy": "2024",
            "prctsCorseDvclsNo": "00",
            "campsBusnsCd": "s1",
            "cgprfEngNm": "Chung Meehyun/Dong Hwan Kim",
            "syySmtDivNm": "2024-1학기",
            "estblDeprtOrd": 40,
            "subjtnbCorsePrcts": "YCA1003-02-00",
            "subjtUnitVal": "1000",
            "srclnLctreLangDivNm": null,
            "cgprfNndsYn": "0",
            "estblDeprtNm": "교양기초(2019학번~) 채플",
            "subjtEngNm": "CHAPEL(3)",
            "orgSysinstDivCd": "H1",
            "lecrmEngNm": "Pre-recorded lecture",
            "lessnSessnDivNm": "학기",
            "subjtSbtlEngNm": null,
            "attflUuid": null,
            "cmptPrctsAmt": 0,
            "tmtcYn": "1",
            "subsrtDivNm": "교기",
            "sysinstDivCd": "H1",
            "lawscSubjcChrtzNm": null
        }
      ]
    """.trimIndent()
}